### ISSUE TITLE
No module named 'tkinter'

### ISSUE THREAD

**Issue by ashua-02** [dhhruv/Vac-Cowin#10]
First and foremost.. this script works brilliantly. Thank you so much for making it!

This is not really a defect but more of a missing info in the installation/getting started. I received the error
" No module named 'tkinter' " after installing everything as per the provided instructions.
To resolve it, I had to install python3-tk. Perhaps you should have that in your requirements file so that it gets downloaded automatically.

Thanks.

**Comment by dhhruv** [comment]
Thanks @ashua-02 for appreciating.

Yeah, for Linux/Mac Users maybe you need to install tkinter explicitly. If you download Python3 directly from it's website then tkinter is already present but if you've Python2 then it's needed to be downloaded. 

I'll keep that in mind and change the requirements file if necessary. It'd be nice if you can add the installation steps in the README and send a PR. Thanks again.
