### ISSUE TITLE
OTP is not getting validated

### ISSUE THREAD

**Issue by Anwit** [dhhruv/Vac-Cowin#11]
Running VacCowin...
Enter the Registered Mobile Number: ********
Successfully Requested OTP for the Mobile Number ******* at 2021-05-25 11:44:33.155353..
Enter OTP (If you don't recieve OTP in 2 minutes, Press Enter to Retry): ******
Validating OTP. Please Wait...
Unable to Validate OTP...
Response: {"message": "Endpoint request timed out"}
Want to Retry with the 9483824079 ? (y/n Default y):

**Comment by dhhruv** [comment]
@Anwit I've updated this issue in the last commit. Please try again. Should work now.
