### ISSUE TITLE
OTP Is Not Getting Validated!

### ISSUE THREAD

**Issue by Aviral-Garg** [dhhruv/Vac-Cowin#12]
OTP is not getting Validated.
Yesterday, It was working fine, But today it is always showing OTP not validated.
Output ::L
_______________________________________________________________________________
Running VacCowin...
Enter the Registered Mobile Number: **********
Successfully Requested OTP for the Mobile Number ********** at 2021-05-25 11:57:12.434363..
Enter OTP (If you don't recieve OTP in 2 minutes, Press Enter to Retry): ******
Validating OTP. Please Wait...
Unable to Validate OTP...
Response: {"message": "Endpoint request timed out"}
Want to Retry with the ********** ? (y/n Default y): y
Successfully Requested OTP for the Mobile Number ********** at 2021-05-25 12:01:14.469154..
Enter OTP (If you don't recieve OTP in 2 minutes, Press Enter to Retry): ******
Validating OTP. Please Wait...
Unable to Validate OTP...
Response: {"message": "Endpoint request timed out"}
Want to Retry with the ********** ? (y/n Default y):
______________________________________________________________________________

**Comment by Anwit** [comment]
They added additional verification it seems. Add origin and referer to the request header

        base_request_header = {
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36",
            'origin': 'https://selfregistration.cowin.gov.in', 'referer': 'https://selfregistration.cowin.gov.in/'
        }

**Comment by Aviral-Garg** [comment]
> They added additional verification it seems. Add origin and referer to the request header
> 
> ```
>     base_request_header = {
>         "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36",
>         'origin': 'https://selfregistration.cowin.gov.in', 'referer': 'https://selfregistration.cowin.gov.in/'
>     }
> ```

Thanks, It worked Now😊

**Comment by dhhruv** [comment]
Thanks @Anwit for resolving this issue. Appreciate that.
