### ISSUE TITLE
Create an Executable file for Windows

### ISSUE THREAD

**Issue by dhhruv** [dhhruv/Vac-Cowin#21]
Tried to build an exe using pyinstaller but that exe doesn't take any input and exits the script sometimes. Plus captcha tests fail if we use the exe.
Nay help regarding the same will be helpful. I tried to build an exe using `pyinstaller -F VacCowin.py`.

**Comment by subho007** [comment]
Since your requirements.txt uses the same dependencies, I can send you a PR similar to https://github.com/bombardier-gif/covid-vaccine-booking/pull/403 for easy windows support.

Although this is not going to be a standalone exe, but very easy for windows users

**Comment by dhhruv** [comment]
Yeah, that's better but I am trying for a standalone executable as that's way more easy then keeping all files.

**Comment by subho007** [comment]
Sure, the only problem with a standalone API is to display a GUI for the captcha, which has some OS dependencies. Let me know if you take the other route, would be happy to contribute then 👍

**Comment by dhhruv** [comment]
> Sure, the only problem with a standalone API is to display a GUI for the captcha, which has some OS dependencies. Let me know if you take the other route, would be happy to contribute then 👍

If somehow we can use the `--hidden-imports` function from `pyinstaller` to add all the dependencies then it may work. I don't know exactly how. Can you help regarding this?
