### ISSUE TITLE
Tk

### ISSUE THREAD

**Issue by sahad752** [dhhruv/Vac-Cowin#22]
The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
maximum recursion depth exceeded

**Comment by dhhruv** [comment]
Thanks for raising this issue @sahad752 . Do you have idea about any alternate library to replace Tkinter to render captcha?

**Comment by rayarindam2111** [comment]
Great improvisation!
The UMANG api, however does not require a captcha for booking vaccine slots.
You can try this project out: [Co-WIN-automated-slot-booking](https://github.com/rayarindam2111/Co-WIN-automated-slot-booking).

**Comment by dhhruv** [comment]
> Great improvisation!
> The UMANG api, however does not require a captcha for booking vaccine slots.
> You can try this project out: [Co-WIN-automated-slot-booking](https://github.com/rayarindam2111/Co-WIN-automated-slot-booking).

Thanks. Yeah, will look into it.
