### ISSUE TITLE
[Question] Does this tool need protected cowin API key?

### ISSUE THREAD

**Issue by arunim2405** [dhhruv/Vac-Cowin#23]
I saw that this tool uses the protected APIs. Don't they require a key obtained from the government?

**Comment by arunim2405** [comment]
For example BENEFICIARIES_URL = "https://cdn-api.co-vin.in/api/v2/appointment/beneficiaries"

**Comment by dhhruv** [comment]
Public API has a caching limit of 30 minutes so you won't get accurate information at real-time hence used protected API. The key shown is used by many projects regarding the same and is authentic.

**Comment by arunim2405** [comment]
I want to integrate this functionality into my app but I don't have a protected key yet. Can you u point me to the file where the key is stored? Thanks!

**Comment by Nakul93** [comment]
You don’t need a key to access protected API. For that you just need a login token which is generated by OTP authentication

**Comment by arunim2405** [comment]
Co-WIN Protected APIs allow any third-party application to access certain restricted information, in order to access, the service providers must agree to the extant “Terms of Service”. All third-party applications that wish to integrate with Co-WIN using Protected APIs should undertake a prescribed integration and testing process with the Co-WIN APIs. For this purpose, the authenticated ASP system administrators will be provided with access to a sandbox environment with staging-level API keys to test integration with the Co-WIN APIs, that the ASP wishes to use in their operations. Only after a successful testing cycle is completed and demonstrated to a competent authority, the ASP will be provided with production-level API keys for their Application. You can test these APIs on the Sandbox Server using API Key - 3sjOr2rmM52GzhpMHjDEE1kpQeRxwFDr4YcBEimi For production access, please register at ASP Registration.
@Nakul93 Now I am just confused🤔

**Comment by arunim2405** [comment]
@dhhruv any remarks on this? Any help would be appreciated.

**Comment by Nakul93** [comment]
I think may be with a API key you get privileged access to protected APIs.
As of now even in this repo we use protected API.

**Comment by dhhruv** [comment]
> @dhhruv any remarks on this? Any help would be appreciated.

Without a secret key, it won't allow you to generate a token (You can try it) which is the basic parameter for protected API's. Hence, if you're not using it then you'd have to go through public API's.
