### ISSUE TITLE
Script does not show correct result

### ISSUE THREAD

**Issue by anshulbharadwaj** [dhhruv/Vac-Cowin#4]
Script is not able to show correct data. It displays message - No options available right now. Next update in x seconds although one option was available which had open slot when viewed through cowin web application. 
Frequency of script is set to 5 seconds.

**Comment by dhhruv** [comment]
Thank you @anshulbharadwaj for raising the issue. It'd be good if you can provide the exact input you gave with screenshots. May help us to look better into it.

**Comment by dhhruv** [comment]
> Script is not able to show correct data. It displays message - No options available right now. Next update in x seconds although one option was available which had open slot when viewed through cowin web application.
> Frequency of script is set to 5 seconds.

Any update @anshulbharadwaj ??
