### ISSUE TITLE
Updating Colors used in Coloring Terminal Texts

### ISSUE THREAD

**Issue by dhhruv** [dhhruv/Vac-Cowin#7]
I've used colorama library to color the terminal texts in my Initial Commit. 

It needs to be updated so that it looks better than before using the same library or other if possible. Use better colors.

**Comment by SehgalNeeraj** [comment]
> I've used colorama library to color the terminal texts in my Initial Commit.
> 
> It needs to be updated so that it looks better than before using the same library or other if possible. Use better colors.

https://www.geeksforgeeks.org/print-colors-python-terminal/

**Comment by dhhruv** [comment]
> > I've used colorama library to color the terminal texts in my Initial Commit.
> > It needs to be updated so that it looks better than before using the same library or other if possible. Use better colors.
> 
> https://www.geeksforgeeks.org/print-colors-python-terminal/

Yeah, I've taken references from the same. What I mean to achieve is which colour will look better to display the information shown on the terminal. If there is any guide or something @SehgalNeeraj . Please let me know.
