### ISSUE TITLE
Certification verification failed

### ISSUE THREAD

**Issue by sync-1203** [dhhruv/Vac-Cowin#9]
HTTPSConnectionPool(host='cdn-api.co-vin.in', port=443): Max retries exceeded with url: /api/v2/appointment/beneficiaries (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
Exiting the Script...
Press any key to continue . . .

Get this error after the script runs for around 40 checks set for 15 second time interval

**Comment by dhhruv** [comment]
There might be a policy or restrictions where you can't make many entries in lesser number of time through API in the [API Setu](https://apisetu.gov.in/public/marketplace/api/cowin). 

I'll look into it and respond.

**Comment by dhhruv** [comment]
> HTTPSConnectionPool(host='cdn-api.co-vin.in', port=443): Max retries exceeded with url: /api/v2/appointment/beneficiaries (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
> Exiting the Script...
> Press any key to continue . . .
> 
> Get this error after the script runs for around 40 checks set for 15 second time interval

@sync-1203 I checked the issue and if you keep a high refresh rate such as >=30 then the problem won't persist. It's probably due to high traffic at the other end.
